DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS daily_summaries;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS sale_items;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenants;
